# Generated by Django 3.1.7 on 2021-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/static/image/default.png', upload_to='product/photo/'),
        ),
    ]
